name: Lighthouse CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: lhci autorun || echo "Lighthouse finished with some errors"

      - name: List .lighthouseci contents (debug)
        run: ls -la .lighthouseci

      - name: Upload Lighthouse HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-html
          path: .lighthouseci/*.html

      - name: Upload Lighthouse JSON reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-json
          path: .lighthouseci/*.json
