name: Lighthouse CI

on:
  workflow_dispatch:  # Ручной запуск из UI GitHub
  push:
    branches:
      - main  # Запуск при пуше в основную ветку
  pull_request:  # Запуск для pull request'ов

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Устанавливаем нужную версию Node.js

      - name: Install dependencies
        run: npm ci --legacy-peer-deps  # Устанавливаем зависимости с флагом для совместимости

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli  # Устанавливаем Lighthouse CI CLI

      - name: Create .lighthouserc.js
        run: |
          echo "module.exports = {
            ci: {
              collect: {
                url: ['https://promelektroservice-react-structure.vercel.app/'],
                numberOfRuns: 3
              },
              upload: {
                target: 'filesystem',
                outputDir: '.lighthouseci/report'
              },
              assert: {
                assertions: {
                  'categories:performance': ['error', { minScore: 0.3 }],
                  'categories:accessibility': ['warn', { minScore: 0.9 }],
                  'categories:seo': ['warn', { minScore: 0.9 }]
                }
              }
            }
          };" > .lighthouserc.js  # Создаём файл конфигурации

      - name: Run Lighthouse CI
        run: lhci autorun  # Запускаем Lighthouse CI

      - name: Check Lighthouse output
        run: ls -R .lighthouseci  # Проверяем результат работы CI

      - name: Upload Lighthouse Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report  # Имя артефакта
          path: .lighthouseci/report/*.html  # Загружаем все HTML отчёты из каталога
