name: Lighthouse CI

on:
  workflow_dispatch:  # ручной запуск из UI GitHub
  push:
    branches:
      - main
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Create .lighthouserc.js
        run: |
          echo "module.exports = {
            ci: {
              collect: {
                url: ['https://promelektroservice-react-structure.vercel.app/'],
                numberOfRuns: 3
              },
              upload: {
                target: 'filesystem',
                outputDir: '.lighthouseci/report'
              },
              assert: {
                assertions: {
                  'categories:performance': ['error', { minScore: 0.3 }],
                  'categories:accessibility': ['warn', { minScore: 0.9 }],
                  'categories:seo': ['warn', { minScore: 0.9 }]
                }
              }
            }
          };" > lighthouserc.js

      - name: Run Lighthouse CI
        run: lhci autorun

      - name: Check Lighthouse output
        run: ls -R .lighthouseci

      - name: Upload Lighthouse Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci/report/*.html
